FROM golang:1.21.4-alpine3.17

RUN mkdir /build

COPY ./resource_server/backend /build

WORKDIR /build

RUN go mod tidy

RUN go build -o main .

EXPOSE 3050

RUN chmod +x ./main

ENTRYPOINT ["./main"]